### ISSUE TITLE
scss support

### ISSUE THREAD

**Issue by paintparty** [ghivert/re-frame-template#2]
The provide example is `src/styles/views.css`, but in reality it is scss. This will trigger syntax error highlighting in most linters with css support.

I tried to change the file extension to scss, but then it does not compile.

Regardless of the above, for some reason I'm not able to get the output I would expect when writing nested scss. Are you able to reproduce this on your end? Thanks!!

From the provided example `src/styles/views.css`:

This:
```
.main a {
  background: #0074D9;

  &:hover {
    background: #7FDBFF;
  }
}
```

Will result in this (valid css):
```
._main_y3g9u_1 a {
  background: #0074d9
}

._main_y3g9u_1 a:hover {
  background: #7fdbff
}
```

However, this:
```
.main {
  a {
    background: #0074D9;

    &:hover {
      background: #7FDBFF;
    }
  }
}
```

Will result in this (which is valid scss, but not valid css ... so will not work as expected):

```
._main_kdhzj_1 {
  a {
    background: #0074d9
  }

  a:hover {
    background: #7fdbff
  }
}
```

One might  expected the output from the two examples to have the same structure?

**Comment by ghivert** [comment]
Hum, that's weird. In fact, it’s [nesting rules from future css](https://preset-env.cssdb.org/features#nesting-rules) and not SCSS. What I don't get is why it isn't applied... I'll take a look during the day to give you a better answer. 😉

**Comment by ghivert** [comment]
Okay, I just checked, and everything is working correctly for me. Are you sure you’re using the version `0.1.4` of `modular-styles` ? There were a bug before making it unable to properly use postcss-preset-env.

**Comment by paintparty** [comment]
Thanks for the quick response and upgrade suggestion!

I cloned your updated repo, but still got the same results as before.  Definitely something weird happening if you got a different result using the nesting example provided above^. I say that because now that I know you are using future css I realized the problem was likely not an upgrade issue. The syntax in the example is actually invalid - the nested `a` selector should be `& a`, which results in the correct output.

Might be a good idea to make it very explicit that this example is using future css syntax.  All of the subtle and not-so-subtle differences between scss, sass, css, and future-css can be quite confusing to developers that don't deal with css everyday. Specifically, a note about this in the CSS Modules section of the readme would be helpful, as well as a comment in the actual `src/styles/views.css` file.

Also, in the example `src/styles/views.css`, the only instance of nesting is on `&:hover` rule, which, unlike nested selectors,  is syntactically identical to SCSS. Maybe a good idea to add an example of a nested class as well as a nested element.

Thanks again for the great project! I look fwd to prototyping w/this and hopefully recommending to my team.

**Comment by ghivert** [comment]
Oh yeah I just got your problem. I red your issue too quickly. 

You’re totally right. The differences between SCSS and PostCSS can be hard to see, especially because nested CSS is a stage 1 feature (and so, still experimental today). 

I need to find a way to be clearer. Maybe we can have an explanation and a tutorial or something like that. 

I’m so glad that you like the project. If you think about something useful, don’t hesitate to open an issue. 😉

**Comment by paintparty** [comment]
🙌
